version: "3"

services:
  aerospike:
    container_name: aerospike
    image: aerospike/aerospike-server:latest
    command: [ "--config-file", "/opt/aerospike/etc/aerospike.conf" ]
    volumes:
      - ./docker/aerospike:/opt/aerospike/etc/
    ports:
      - 3000:3000 # service port, for client connections
      - 3001:3001 # fabric port, for cluster communication
      - 3002:3002 # mesh port, for cluster heartbeat
      - 3003:3003 # info port

  aerospikeui:
    container_name: aerospikeui
    image: mrbar42/aerospike-amc
    ports:
      - 8081:8081 # web interface port... go to http://localhost:8081 and enter "aerospike" as the host
